import { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Checkbox, FormControlLabel, IconButton, MenuItem, Switch, TextField, Tooltip } from '@mui/material';
import { AddRounded, EditRounded, PrintRounded, RefreshRounded } from '@mui/icons-material';
import { api } from '../api/client.js';
import { PageHeader } from '../components/navigation/PageHeader.jsx';
import { DataTable } from '../components/data/DataTable.jsx';
import { FilterPanel } from '../components/forms/FilterPanel.jsx';
import { EntityDrawer } from '../components/forms/EntityDrawer.jsx';
import { Field } from '../components/forms/Field.jsx';
import { FormSection } from '../components/forms/FormSection.jsx';
import { LoadingState } from '../components/feedback/LoadingState.jsx';
import { AppSnackbar } from '../components/feedback/AppSnackbar.jsx';
import { StatusChip } from '../components/data/StatusChip.jsx';
import { money, number } from '../utils/formatters.js';

const baseForm = {
  name: '', sku: '', barcode: '', category_id: '', description: '', is_active: true, can_be_sold: true, can_be_preordered: true,
  default_preorder_deposit_pct: 50, default_pickup_method: 'walk_in', low_stock_threshold: 5, purchase_cost: '', notes: '', is_book: false,
  book_type: '', school_grade: '', subject: '', teacher: '', publisher: '', release_year: '', term: 'first', educational_classification: 'external_book', prices: {}
};
export default function Products() {
  const [rows, setRows] = useState([]); const [categories, setCategories] = useState([]); const [tiers, setTiers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ q: '', categoryId: '', stock: 'all', type: 'all', active: 'all' });
  const [drawer, setDrawer] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(baseForm); const [saving, setSaving] = useState(false); const [toast, setToast] = useState(null);
  const [qrProduct, setQrProduct] = useState(null); const [qrForm, setQrForm] = useState({ quantity: 1, label_size: 'medium' });

  const loadRefs = async () => { const [c,t] = await Promise.all([api.get('/api/categories?activeOnly=false'), api.get('/api/admin/price-tiers?activeOnly=false')]); setCategories(c.data || []); setTiers(t.data || []); };
  const load = async () => { setLoading(true); try { const q = new URLSearchParams(); if (filters.q) q.set('q', filters.q); if (filters.categoryId) q.set('categoryId', filters.categoryId); q.set('activeOnly', 'false'); let data = (await api.get(`/api/products?${q}`)).data || []; if (filters.stock === 'low') data = data.filter(p => p.stock > 0 && p.stock <= p.low_stock_threshold); if (filters.stock === 'out') data = data.filter(p => p.stock <= 0); if (filters.stock === 'available') data = data.filter(p => p.stock > 0); if (filters.type === 'book') data = data.filter(p => p.is_book === 1); if (filters.type === 'general') data = data.filter(p => p.is_book !== 1); if (filters.active === 'active') data = data.filter(p => p.is_active === 1); if (filters.active === 'inactive') data = data.filter(p => p.is_active !== 1); setRows(data); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { loadRefs().catch(e => setError(e.message)); load(); }, []);
  const resetFilters = () => { setFilters({ q: '', categoryId: '', stock: 'all', type: 'all', active: 'all' }); setTimeout(load, 0); };
  const openNew = () => { setEditing(null); setForm({ ...baseForm, category_id: categories[0]?.id || '', prices: {} }); setDrawer(true); };
  const openEdit = async (row) => { setSaving(true); try { const p = (await api.get(`/api/products/${row.id}`)).data; const priceMap = {}; (p.prices || []).forEach(x => { priceMap[x.price_tier_id] = x.price / 100; }); setForm({
      name: p.name || '', sku: p.sku || '', barcode: p.barcode || '', category_id: p.category_id || '', description: p.description || '', is_active: Boolean(p.is_active), can_be_sold: Boolean(p.can_be_sold), can_be_preordered: Boolean(p.can_be_preordered), default_preorder_deposit_pct: p.default_preorder_deposit_pct ?? 50, default_pickup_method: p.default_pickup_method || 'walk_in', low_stock_threshold: p.low_stock_threshold ?? 5, purchase_cost: (p.purchase_cost || 0) / 100, notes: p.notes || '', is_book: Boolean(p.book_details), book_type: p.book_details?.book_type || '', school_grade: p.book_details?.school_grade || '', subject: p.book_details?.subject || '', teacher: p.book_details?.teacher || '', publisher: p.book_details?.publisher || '', release_year: p.book_details?.release_year || '', term: p.book_details?.term || 'first', educational_classification: p.book_details?.educational_classification || 'external_book', prices: priceMap
    }); setEditing(p); setDrawer(true); } catch (e) { setToast({ severity: 'error', message: e.message }); } finally { setSaving(false); } };
  const payload = () => ({
    name: form.name.trim(), sku: form.sku.trim(), barcode: form.barcode.trim() || null, category_id: Number(form.category_id), description: form.description || null,
    is_active: form.is_active ? 1 : 0, can_be_sold: form.can_be_sold ? 1 : 0, can_be_preordered: form.can_be_preordered ? 1 : 0,
    default_preorder_deposit_pct: Number(form.default_preorder_deposit_pct), default_pickup_method: form.default_pickup_method, low_stock_threshold: Number(form.low_stock_threshold), purchase_cost: Math.round(Number(form.purchase_cost || 0) * 100), notes: form.notes || null,
    is_book: form.is_book ? 1 : 0,
    book_details: form.is_book ? { book_type: form.book_type || null, school_grade: form.school_grade || null, subject: form.subject || null, teacher: form.teacher || null, publisher: form.publisher || null, release_year: form.release_year ? Number(form.release_year) : null, term: form.term, educational_classification: form.educational_classification } : null,
    prices: tiers.map(t => ({ price_tier_id: t.id, price: Math.round(Number(form.prices[t.id] || 0) * 100) }))
  });
  const save = async () => { if (!form.name.trim() || !form.sku.trim() || !form.category_id) return setToast({ severity: 'error', message: 'اسم المنتج ورمز SKU والتصنيف حقول مطلوبة.' }); setSaving(true); try { if (editing) await api.patch(`/api/admin/products/${editing.id}`, payload()); else await api.post('/api/admin/products', payload()); setToast({ message: editing ? 'تم تحديث المنتج.' : 'تم إنشاء المنتج.' }); setDrawer(false); await load(); } catch (e) { setToast({ severity: 'error', message: e.message }); } finally { setSaving(false); } };
  const printQr = async () => { setSaving(true); try { const result = (await api.post(`/api/admin/products/${qrProduct.id}/qr-labels`, qrForm)).data; const url = `/api/admin/print-job/${encodeURIComponent(result.token)}?qty=${result.quantity}&size=${result.label_size}`; window.open(url, '_blank', 'noopener,noreferrer'); setQrProduct(null); setToast({ message: 'تم تجهيز ملصقات المنتج للطباعة.' }); } catch (e) { setToast({ severity: 'error', message: e.message }); } finally { setSaving(false); } };
  const columns = useMemo(() => [
    { key: 'name', label: 'اسم المنتج', render: r => <div><strong>{r.name}</strong><div className="a4-muted a4-ltr" style={{ fontSize: '.67rem', textAlign: 'right', direction: 'ltr' }}>{r.sku}</div></div> },
    { key: 'category_name', label: 'التصنيف' }, { key: 'barcode', label: 'الباركود', render: r => <span className="a4-ltr">{r.barcode || '—'}</span> },
    { key: 'purchase_cost', label: 'تكلفة الشراء', render: r => money(r.purchase_cost) }, { key: 'stock', label: 'المخزون', render: r => <strong>{number(r.stock)}</strong> },
    { key: 'open_preorders', label: 'الحجوزات', render: r => number(r.open_preorders) }, { key: 'type', label: 'النوع', render: r => r.is_book ? 'كتاب' : 'منتج عام' },
    { key: 'status', label: 'الحالة', render: r => <StatusChip status={r.is_active ? 'active' : 'inactive'} label={r.is_active ? 'نشط' : 'معطل'}/> },
    { key: 'actions', label: 'الإجراءات', render: r => <div className="table-actions"><Tooltip title="تعديل"><IconButton size="small" onClick={() => openEdit(r)}><EditRounded fontSize="small"/></IconButton></Tooltip><Tooltip title="طباعة رمز المنتج"><IconButton size="small" onClick={() => setQrProduct(r)}><PrintRounded fontSize="small"/></IconButton></Tooltip></div> }
  ], []);
  return <div className="a4-page"><PageHeader title="المنتجات" description="إدارة المنتجات العامة والكتب والأسعار والمخزون والحجز المسبق بدون صور." actions={<><Button variant="outlined" startIcon={<RefreshRounded/>} onClick={load}>تحديث</Button><Button variant="contained" startIcon={<AddRounded/>} onClick={openNew}>منتج جديد</Button></>}/><FilterPanel resultCount={rows.length} onApply={load} onReset={resetFilters}><Field label="البحث"><TextField value={filters.q} onChange={e => setFilters(v => ({ ...v, q: e.target.value }))} placeholder="الاسم أو SKU أو الباركود"/></Field><Field label="التصنيف"><TextField select value={filters.categoryId} onChange={e => setFilters(v => ({ ...v, categoryId: e.target.value }))}><MenuItem value="">الكل</MenuItem>{categories.map(c => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField></Field><Field label="نوع المنتج"><TextField select value={filters.type} onChange={e => setFilters(v => ({ ...v, type: e.target.value }))}><MenuItem value="all">الكل</MenuItem><MenuItem value="book">كتب</MenuItem><MenuItem value="general">منتجات عامة</MenuItem></TextField></Field><Field label="حالة المخزون"><TextField select value={filters.stock} onChange={e => setFilters(v => ({ ...v, stock: e.target.value }))}><MenuItem value="all">الكل</MenuItem><MenuItem value="available">متوفر</MenuItem><MenuItem value="low">مخزون منخفض</MenuItem><MenuItem value="out">نفد المخزون</MenuItem></TextField></Field><Field label="حالة المنتج"><TextField select value={filters.active} onChange={e => setFilters(v => ({ ...v, active: e.target.value }))}><MenuItem value="all">الكل</MenuItem><MenuItem value="active">نشط</MenuItem><MenuItem value="inactive">معطل</MenuItem></TextField></Field></FilterPanel>{error && <Alert severity="error">{error}</Alert>}<section className="a4-page-section">{loading ? <LoadingState/> : <DataTable columns={columns} rows={rows} mobilePrimary={r => r.name}/>}</section>
    <EntityDrawer wide open={drawer} title={editing ? 'تعديل المنتج' : 'إضافة منتج'} subtitle="جميع الحقول مرتبة بدون عناوين عائمة أو نوتش داخل الإطارات." onClose={() => setDrawer(false)} onSubmit={save} loading={saving}>
      <FormSection title="البيانات الأساسية"><div className="a4-form-grid"><Field label="اسم المنتج" required><TextField value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))}/></Field><Field label="رمز SKU" required><TextField slotProps={{ htmlInput: { dir: 'ltr' } }} value={form.sku} onChange={e => setForm(v => ({ ...v, sku: e.target.value }))}/></Field><Field label="الباركود"><TextField slotProps={{ htmlInput: { dir: 'ltr' } }} value={form.barcode} onChange={e => setForm(v => ({ ...v, barcode: e.target.value }))}/></Field><Field label="التصنيف" required><TextField select value={form.category_id} onChange={e => setForm(v => ({ ...v, category_id: e.target.value }))}>{categories.map(c => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField></Field><Field className="full" label="الوصف"><TextField multiline minRows={2} value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))}/></Field></div></FormSection>
      <FormSection title="قواعد البيع والحجز"><div className="a4-form-grid"><Field label="تكلفة الشراء"><TextField type="number" slotProps={{ htmlInput: { min: 0, step: .01 } }} value={form.purchase_cost} onChange={e => setForm(v => ({ ...v, purchase_cost: e.target.value }))}/></Field><Field label="حد تنبيه المخزون"><TextField type="number" slotProps={{ htmlInput: { min: 0 } }} value={form.low_stock_threshold} onChange={e => setForm(v => ({ ...v, low_stock_threshold: e.target.value }))}/></Field><Field label="نسبة عربون الحجز"><TextField type="number" slotProps={{ htmlInput: { min: 0, max: 100 } }} value={form.default_preorder_deposit_pct} onChange={e => setForm(v => ({ ...v, default_preorder_deposit_pct: e.target.value }))}/></Field><Field label="طريقة الاستلام الافتراضية"><TextField select value={form.default_pickup_method} onChange={e => setForm(v => ({ ...v, default_pickup_method: e.target.value }))}><MenuItem value="walk_in">استلام من المكتبة</MenuItem><MenuItem value="delivery">توصيل</MenuItem></TextField></Field><Field className="full" label="حالة المنتج"><div className="a4-actions"><FormControlLabel control={<Switch checked={form.is_active} onChange={e => setForm(v => ({ ...v, is_active: e.target.checked }))}/>} label="نشط"/><FormControlLabel control={<Switch checked={form.can_be_sold} onChange={e => setForm(v => ({ ...v, can_be_sold: e.target.checked }))}/>} label="قابل للبيع المباشر"/><FormControlLabel control={<Switch checked={form.can_be_preordered} onChange={e => setForm(v => ({ ...v, can_be_preordered: e.target.checked }))}/>} label="قابل للحجز المسبق"/></div></Field></div></FormSection>
      <FormSection title="فئات الأسعار" description="السعر بالجنيه المصري، ويحفظ داخلياً بوحدة القرش."><div className="a4-form-grid">{tiers.map(t => <Field key={t.id} label={t.name}><TextField type="number" slotProps={{ htmlInput: { min: 0, step: .01 } }} value={form.prices[t.id] ?? ''} onChange={e => setForm(v => ({ ...v, prices: { ...v.prices, [t.id]: e.target.value } }))}/></Field>)}</div></FormSection>
      <FormSection title="بيانات الكتاب الاختيارية"><FormControlLabel control={<Checkbox checked={form.is_book} onChange={e => setForm(v => ({ ...v, is_book: e.target.checked }))}/>} label="هذا المنتج كتاب أو مادة تعليمية"/>{form.is_book && <div className="a4-form-grid" style={{ marginTop: 12 }}><Field label="نوع الكتاب"><TextField value={form.book_type} onChange={e => setForm(v => ({ ...v, book_type: e.target.value }))}/></Field><Field label="الصف الدراسي"><TextField value={form.school_grade} onChange={e => setForm(v => ({ ...v, school_grade: e.target.value }))}/></Field><Field label="المادة"><TextField value={form.subject} onChange={e => setForm(v => ({ ...v, subject: e.target.value }))}/></Field><Field label="المدرس"><TextField value={form.teacher} onChange={e => setForm(v => ({ ...v, teacher: e.target.value }))}/></Field><Field label="دار النشر"><TextField value={form.publisher} onChange={e => setForm(v => ({ ...v, publisher: e.target.value }))}/></Field><Field label="سنة الإصدار"><TextField type="number" value={form.release_year} onChange={e => setForm(v => ({ ...v, release_year: e.target.value }))}/></Field><Field label="الترم"><TextField select value={form.term} onChange={e => setForm(v => ({ ...v, term: e.target.value }))}><MenuItem value="first">الترم الأول</MenuItem><MenuItem value="second">الترم الثاني</MenuItem></TextField></Field><Field label="التصنيف التعليمي"><TextField select value={form.educational_classification} onChange={e => setForm(v => ({ ...v, educational_classification: e.target.value }))}><MenuItem value="external_book">كتاب خارجي</MenuItem><MenuItem value="school_book">كتاب مدرسي</MenuItem><MenuItem value="booklet">مذكرة</MenuItem><MenuItem value="notes">ملازم</MenuItem></TextField></Field></div>}</FormSection>
      <FormSection title="ملاحظات داخلية"><Field><TextField multiline minRows={3} value={form.notes} onChange={e => setForm(v => ({ ...v, notes: e.target.value }))}/></Field></FormSection>
    </EntityDrawer>
    <EntityDrawer open={Boolean(qrProduct)} title="طباعة ملصقات المنتج" subtitle={qrProduct?.name} onClose={() => setQrProduct(null)} onSubmit={printQr} submitLabel="فتح صفحة الطباعة" loading={saving}><div className="a4-form-grid"><Field label="عدد الملصقات" required><TextField type="number" slotProps={{ htmlInput: { min: 1, max: 500 } }} value={qrForm.quantity} onChange={e => setQrForm(v => ({ ...v, quantity: Number(e.target.value) }))}/></Field><Field label="مقاس الملصق"><TextField select value={qrForm.label_size} onChange={e => setQrForm(v => ({ ...v, label_size: e.target.value }))}><MenuItem value="small">صغير</MenuItem><MenuItem value="medium">متوسط</MenuItem><MenuItem value="large">كبير</MenuItem></TextField></Field></div></EntityDrawer>
    <AppSnackbar state={toast} onClose={() => setToast(null)}/>
  </div>;
}
