import { useEffect, useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, TextField, Tooltip } from '@mui/material';
import { CheckRounded, CloseRounded, RefreshRounded } from '@mui/icons-material';
import { api } from '../api/client.js';
import { PageHeader } from '../components/navigation/PageHeader.jsx';
import { DataTable } from '../components/data/DataTable.jsx';
import { StatusChip } from '../components/data/StatusChip.jsx';
import { Field } from '../components/forms/Field.jsx';
import { LoadingState } from '../components/feedback/LoadingState.jsx';
import { AppSnackbar } from '../components/feedback/AppSnackbar.jsx';
import { dateTime, money } from '../utils/formatters.js';

export default function Shifts(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[action,setAction]=useState(''),[notes,setNotes]=useState(''),[saving,setSaving]=useState(false),[toast,setToast]=useState(null);
 const load=async()=>{setLoading(true);try{setRows((await api.get('/api/shifts/pending-review')).data||[]);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const submit=async()=>{setSaving(true);try{await api.post(`/api/shifts/${selected.id}/${action}`,{adminNotes:notes});setToast({message:action==='approve'?'تم اعتماد الشيفت.':'تم رفض الشيفت.'});setSelected(null);setAction('');setNotes('');await load();}catch(e){setToast({severity:'error',message:e.message});}finally{setSaving(false);}};
 const columns=[{key:'id',label:'رقم الشيفت',render:r=>`#${r.id}`},{key:'cashier_name',label:'الكاشير'},{key:'opened_at',label:'وقت الفتح',render:r=>dateTime(r.opened_at)},{key:'closed_at',label:'طلب الإغلاق',render:r=>dateTime(r.closed_at)},{key:'system_total_cash',label:'الكاش المتوقع',render:r=>money(r.system_total_cash)},{key:'cashier_declared_cash',label:'الكاش الفعلي',render:r=>money(r.cashier_declared_cash)},{key:'difference',label:'الفرق',render:r=>{const d=(r.cashier_declared_cash||0)-(r.system_total_cash||0);return <strong style={{color:d===0?'inherit':d<0?'#d64242':'#c87900'}}>{money(d)}</strong>}},{key:'status',label:'الحالة',render:r=><StatusChip status={r.status}/>},{key:'actions',label:'الإجراءات',render:r=><div className="table-actions"><Tooltip title="اعتماد"><IconButton color="success" size="small" onClick={()=>{setSelected(r);setAction('approve')}}><CheckRounded fontSize="small"/></IconButton></Tooltip><Tooltip title="رفض"><IconButton color="error" size="small" onClick={()=>{setSelected(r);setAction('reject')}}><CloseRounded fontSize="small"/></IconButton></Tooltip></div>}];
 return <div className="a4-page"><PageHeader title="مراجعة الشيفتات" description="مراجعة المبالغ المتوقعة والفعلية ثم اعتماد أو رفض التقفيل." actions={<Button variant="outlined" startIcon={<RefreshRounded/>} onClick={load}>تحديث</Button>}/>{error&&<Alert severity="error">{error}</Alert>}<section className="a4-page-section">{loading?<LoadingState/>:<DataTable columns={columns} rows={rows} emptyTitle="لا توجد شيفتات للمراجعة" emptyDescription="كل طلبات التقفيل تمت مراجعتها." mobilePrimary={r=>`شيفت #${r.id}`}/>}</section><Dialog open={Boolean(selected)} onClose={()=>!saving&&setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>{action==='approve'?'اعتماد تقفيل الشيفت':'رفض تقفيل الشيفت'} #{selected?.id}</DialogTitle><DialogContent dividers>{selected&&<><div className="a4-grid a4-grid--two a4-grid--section-gap"><div className="metric-card"><div className="metric-card__copy"><span className="metric-card__label">المتوقع</span><strong>{money(selected.system_total_cash)}</strong></div></div><div className="metric-card"><div className="metric-card__copy"><span className="metric-card__label">الفعلي</span><strong>{money(selected.cashier_declared_cash)}</strong></div></div></div><Field label="ملاحظات الأدمن" required={action==='reject'}><TextField multiline minRows={4} fullWidth value={notes} onChange={e=>setNotes(e.target.value)} placeholder="اكتب سبب الرفض أو ملاحظات الاعتماد"/></Field></>}</DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>إلغاء</Button><Button variant="contained" color={action==='reject'?'error':'success'} onClick={submit} disabled={saving||action==='reject'&&!notes.trim()}>{saving?'جاري التنفيذ...':action==='approve'?'اعتماد الشيفت':'رفض الشيفت'}</Button></DialogActions></Dialog><AppSnackbar state={toast} onClose={()=>setToast(null)}/></div>;
}
